Add Tool Interaction Views
StanfordSpezi/SpeziChat pull request #18
Opened 2024-12-06 18:10 UTC by LeonNissen

# *Name of the PR*

## :recycle: Current situation & Problem
*Link any open issues or pull requests (PRs) related to this PR. Please ensure that all non-trivial PRs are first tracked and discussed in an existing GitHub issue or discussion.*

## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented or links to the documentation if it appends or changes the public interface.*

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage contributors to document your reasoning and changes using in-line documentation.* 

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
*This section describes important information about the tests and why some elements might not be testable.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2024-12-09 01:11 UTC, PSchmiedmayer approved these changes
Thank you for the improvements; it does a non-breaking fix for what we want to do. In the long run, we should add a more extensible structure for custom views in the chat.

I would also defer to @philippzagar for some additional input.

2024-12-09 01:11 UTC, PSchmiedmayer commented on Sources/SpeziChat/Models/ChatEntity.swift
> +        case assistantToolResponse
Thank you for the additions here.

We should create an extensive issue that documents a future extension into a more generalized setup where we can use static functions on the Role type that will be transformed into struct conforming to View to allow an easy extension or additional types for everyone that is using Spezi chat while we provide default implementations for the roles that we have detailed here.

2024-12-11 11:05 UTC, philippzagar commented on Sources/SpeziChat/Models/ChatEntity.swift
> +        case assistantToolResponse
Fully agree with Paul here, we should do that in an extensive GitHub issue.

2024-12-11 11:21 UTC, philippzagar requested changes
Thanks for the PR @LeonNissen! 🚀 
As @PSchmiedmayer already mentioned: We should definitely create a GitHub issue that lays out the future extension of `Role`s into a more generalized setup.
Also, please add a small UI test to keep up the coverage tests that are failing

2024-12-11 11:21 UTC, philippzagar commented on Sources/SpeziChat/ChatView+SpeechButton.swift
> +    @Previewable @State var chat: Chat = .init(
Quickly made these changes in order to resolve warnings!

2024-12-11 11:21 UTC, philippzagar commented on Sources/SpeziChat/Resources/Localizable.xcstrings
> +    "Equal sign" : {
Missing translations?

2024-12-11 11:21 UTC, philippzagar commented on Sources/SpeziChat/ToolInteractionView.swift
> +struct ToolInteractionView: View {
We should add a small UI test for the new tool interactions view

2024-12-11 21:44 UTC, philippzagar approved these changes
Thanks @LeonNissen for this PR and adding the tests, looks graet! 🚀

2024-12-11 21:46 UTC, philippzagar commented
@LeonNissen Just noticed that the commits on this branch are not properly signed, therefore preventing a merge. 
Two options: Either you retroactively sign the commits and force push to the respective branch, or @PSchmiedmayer quickly merges the PR by bypassing the merge checks.

2024-12-12 00:32 UTC, merged