Initial setup of repository
StanfordSpezi/SpeziChat pull request #2
Opened 2023-11-13 22:13 UTC by philippzagar

# Initial setup of repository

## :recycle: Current situation & Problem
Currently, the repo is mostly empty except for a template package.

## :gear: Release Notes 
- Initial setup of the `SpeziChat` repo which previously was a target in the [SpeziML](https://github.com/StanfordSpezi/SpeziML) repo
- Improved README and documentation via DocC

## :books: Documentation
--

## :white_check_mark: Testing
UI Tests are included

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2023-11-13 22:37 UTC, philippzagar commented
@PSchmiedmayer Same as in https://github.com/StanfordSpezi/SpeziSpeech/pull/2, I think what's left here is a proper DOI as well as the push to the Swift Package Index (the latter one can probably only be done after merging to `main`, the links to the index are already set correctly, that's thy the Markdown Link Check fails).

2023-11-15 06:28 UTC, PSchmiedmayer requested changes
Thank you for adding the code to this repo from Spezi ML and adding all the documentation surrounding it!

Similar to the Speech PR; I had a few comments that would be great to be addressed before we merge the PR.

The overall PR looks very great and all the documentation added is more than appreciated! 🚀

2023-11-15 06:28 UTC, PSchmiedmayer commented on .github/workflows/build-and-test.yml
All the same comments from https://github.com/StanfordSpezi/SpeziSpeech/pull/2/files#diff-bc668a2c9f2299cef15b222055b4b4d5311646caec2e7610e540cee18ae9b948 also apply to this file.

2023-11-15 06:28 UTC, PSchmiedmayer commented on .github/workflows/pull_request.yml
> -
This diff is not necessary.

2023-11-15 06:28 UTC, PSchmiedmayer commented on CITATION.cff
Same comments as in https://github.com/StanfordSpezi/SpeziSpeech/pull/2/files#diff-9b9f76394a441ff40bf8d7a0f3e0ddd7ae97abfa9a9a6abaedccf76dc4d51295.

2023-11-15 06:28 UTC, PSchmiedmayer commented on CONTRIBUTORS.md
> +* [Adrit Rao](https://github.com/AdritRao)
🎉🚀

2023-11-15 06:28 UTC, PSchmiedmayer commented on Package.swift
> +        .package(url: "https://github.com/StanfordSpezi/SpeziSpeech", branch: "feat/init-setup")    // .upToNextMinor(from: "0.1.0")
TODO to fix this once the Speech PR is merged.

2023-11-15 06:28 UTC, PSchmiedmayer commented on README.md
The same comments as the ones in https://github.com/StanfordSpezi/SpeziSpeech/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 apply to this README as well 👍

2023-11-15 06:28 UTC, PSchmiedmayer commented on README.md
> +[![](https://img.shields.io/endpoint?url=https%3A%2F%2Fswiftpackageindex.com%2Fapi%2Fpackages%2FStanfordSpezi%2FSpeziChat%2Fbadge%3Ftype%3Dplatforms)](https://swiftpackageindex.com/StanfordSpezi/Spez
The same comments as the ones 
```suggestion
```

2023-11-15 06:28 UTC, PSchmiedmayer commented on README.md
> +|[`ChatView`](https://swiftpackageindex.com/stanfordspezi/spezichat/documentation/spezichat/chatview)|[`ChatView`](https://swiftpackageindex.com/stanfordspezi/spezichat/documentation/spezichat/chatvi
Thank you for all the screenshots, very nice!!

2023-11-15 06:28 UTC, PSchmiedmayer commented on README.md
> +The [`ChatView`](https://swiftpackageindex.com/stanfordspezi/spezichat/documentation/spezichat/chatview) provides a basic reusable chat view which includes a message input field. The input can be eit
Thank you for all the examples in here; great job!!

2023-11-15 06:28 UTC, PSchmiedmayer commented on Sources/SpeziChat/SpeziChat.docc/SpeziChat.md
Thank you for the nice DocC article here!!

2023-11-15 06:28 UTC, PSchmiedmayer commented on Tests/UITests/TestApp/ChatTestView.swift
Nice to see the example implementation here! 🚀

2023-11-16 07:35 UTC, philippzagar commented
@PSchmiedmayer PR is ready for another round of review. The only left TODO will be incorporated once SpeziSpeech is merged and tagged.

2023-11-16 16:31 UTC, PSchmiedmayer approved these changes
Thank you @philippzagar; this looks great!

2023-11-17 19:13 UTC, philippzagar commented
@PSchmiedmayer Similar to https://github.com/StanfordSpezi/SpeziSpeech, please merge the PR and tag a release :)

2023-11-20 17:05 UTC, merged

2023-11-20 17:08 UTC, PSchmiedmayer commented
Thank you for all the setup here @philippzagar! I have merged the PR, tagged a release, and it should also start the process of creating a DOI for the repo.

Feel free to create a similar PR to Spezi Speech once all the processes are finished. Thank you for all the work in setting these things up!

2023-11-20 17:10 UTC, philippzagar commented
Thanks @PSchmiedmayer, will add the DOI as well as SPI things soon!