New `Binding<Bool>` and animation in `ChatView` for three-dots typing indicator
StanfordSpezi/SpeziChat pull request #6
Opened 2023-12-19 22:00 UTC by MatthewTurk247

# Chat Typing Indicator

## :recycle: Current situation & Problem
As stated in [#15](https://github.com/StanfordSpezi/SpeziLLM/issues/15), there is currently no visual indicator when a user input is being processed by the LLM on the other end. This can lead to a confusing experience, as the user may prematurely send another message or exit the app, believing that the chat has stopped responding.

## :gear: Release Notes 
- Extended `MessageView` to add the typing indicator animation, which is visible depending on a new variable called `displayTypingIndicator`.
- Typing indicator displays three gray dots in a message bubble at the bottom of the chat when an LLM response is pending (i.e., the first token has not yet been streamed).
- Each dot appears and disappears in a sequential, wave-like pattern, creating the impression that the dots are bouncing or pulsing one after the other from left to right. The animation loops continuously until `displayTypingIndicator` is set to `false`.

## :books: Documentation
Documentation for the new initializer associated with this update is provided as an in-code comment.

## :white_check_mark: Testing
Manually tested with SwiftUI Previews.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2023-12-20 02:37 UTC, PSchmiedmayer commented
Thank you @MatthewTurk247 for your first PR in the Spezi ecosystem! I have asked @philippzagar to take a first look at the changes and provide some feedback from his side, and I also started the automated CI build to get linting and other results 👍

2023-12-21 21:59 UTC, MatthewTurk247 commented
Thanks to everyone for the support! I look forward to feedback from code review. On another note, I have heretofore been running `swiftlint` manually in the project directory, but why don't we add SwiftLint to the `Package.swift` manifest to receive warnings [directly in Xcode](https://github.com/realm/SwiftLint?tab=readme-ov-file#swift-package)? Figured that might make it easier to adhere to formatting standards if it's not too distracting.

2024-01-04 08:39 UTC, philippzagar requested changes
Thanks a lot @MatthewTurk247 for the great additions to SpeziChat, it’s a very useful feature! 🚀 
Also, please excuse the late feedback, I took some time off during the christmas break. Happy new year! 🥳 

Some additional points regarding my review of your PR:
- The additions are already in great shape with good documentation, thanks for that!
- Please write a small UI test for the typing indicator, this helps a lot with early detection of regressions in our code base
- Please adjust the rest of the in-line DocC documentation, e.g. within the ChatView
- Please adjust the SpeziChat DocC article accordingly, maybe even the README

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/MessageView.swift
> +public struct MessageView<Content: View>: View {
I don’t think we should make this view generic. Actually, from my perspective, it’s a bit dangerous to let the developer pass an arbitrary view as content into a message view. For now, I would leave it at the String-based only content

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/TypingIndicator.swift
> +public struct TypingIndicator: View {
Nicely coded typing indicator, I like it!

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/TypingIndicator.swift
> +/// }
Thanks for the great documentation!

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/TypingIndicator.swift
> +    @Binding var isVisible: Bool
In my opinion, this view should only display the three-dot typing indicator and not decide about the actual presentation of the typing indicator. As stated in my feedback for `MessagesView`, I would move the presentation logic into the `MessagesView` or `ChatView`

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/TypingIndicator.swift
> +//
It would be a good idea to move the `TypingIndicator` into a `Helpers` directory (feel free to adjust the naming), together with `MessageInputViewHeightKey`

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +                        TypingIndicator($displayTypingIndicator)
I would place the entire code of displaying the typing indicator in here (alternatively the `ChatView`, but this would lead to some problems with the auto scrolling as far as I’m seeing, feel free to check that out!), therefore there’s no need to pass down the Binding through 3 levels of view hierarchies to the `TypingIndicator`.

2024-01-04 08:39 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
>      public init(
I would suggest that the `MessagesView` offers two presentation modes that are configurable via the initializer(s):

- Automatically displaying the typing indicator if the last message in the chat is from the user but there’s not yet a response (not even partial) from the assistant. This would be incredible useful for chat-based LLM interactions, e.g. in SpeziLLM
- Manually adjusting the binding that presents the typing indicator.

2024-01-05 18:46 UTC, MatthewTurk247 commented on Sources/SpeziChat/MessageView.swift
> +public struct MessageView<Content: View>: View {
That makes sense. The idea was to make `MessageView` capable of presenting content in any modality rather than only text, but maybe that is a feature for down the line. We could also use an enum or something to specify the kind of content with which `MessageView` is intended to be used. But anyway, I will remove the generic and adjust the rest of the code accordingly.

2024-01-05 18:48 UTC, MatthewTurk247 commented on Sources/SpeziChat/TypingIndicator.swift
> +    @Binding var isVisible: Bool
Gotcha. Will do.

2024-01-08 17:00 UTC, MatthewTurk247 commented on Sources/SpeziChat/TypingIndicator.swift
> +/// }
Glad you like it—and I will be sure to update this after removing the presentation logic from the view.

2024-01-08 19:51 UTC, MatthewTurk247 commented on Sources/SpeziChat/MessagesView.swift
>      public init(
Done. I wrote an enum called `LoadingDisplayMode` with `automatic` and `manual` cases for this approach. Thanks for the feedback!

2024-01-11 18:15 UTC, MatthewTurk247 commented
Question for @philippzagar, how do you suggest I write the UI test for `TypingIndicator`? Right now my approach is to add an accessibility identifier (with corresponding details in the localization file), but my `XCUIElementQuery` doesn't seem to be working as expected. Another complication could be that, for the test I am running in the simulator, `TypingIndicator` is only in the view for maybe half a second at most before it is replaced with an assistant message.

2024-01-11 18:24 UTC, philippzagar commented
> ntifier (with corresponding details in the localization fi

@MatthewTurk247 
Great to see that you're making progress on the PR! 🚀 

Regarding the UI Test: So, as far as I'm seeing, you already implemented the initializer in the `MessagesView` that takes a `Binding` as an argument (within an enum associated value). Just implement a new test view (e.g. see in `SpeziViews`: https://github.com/StanfordSpezi/SpeziViews) that utilizes this initializer and passes down a manual `Binding`. The `Binding` can then be adjusted (turned on/off) by e.g. a button in the navigation bar.

To identify the element, an accessibility identifier seems like a reasonable choice. With my suggestions made above, you should then be able to implement a comprehensive UI test!

2024-01-18 23:08 UTC, MatthewTurk247 commented
@PSchmiedmayer—changing `try await Task.sleep(for: .seconds(1))` to `try await Task.sleep(for: .seconds(5))` worked! Now with a slightly adjusted position for the accessibility identifier in `TypingIndicator.swift` and a couple of additional lines in `TestAppUITests.swift`, the updated `testChat` is passing as expected.

2024-01-19 06:39 UTC, PSchmiedmayer commented
Very nice @MatthewTurk247; thank you for adapting the UI tests accordingly and great to see that our approach is working!

I'll let @philippzagar take a final look at the PR and approve it if there are no other elements that should be addressed 🚀

2024-01-19 22:17 UTC, philippzagar requested changes
Thanks @MatthewTurk247 for the enhancements, looks great! 🚀 

I left a few comments that should get this PR close to the finish line! Looking forward to your implementations!

2024-01-19 22:17 UTC, philippzagar commented on Sources/SpeziChat/Resources/Localizable.xcstrings
> +      "extractionState" : "manual",
Ensure that you don't have any `manual` extractionStates in the String catalog -> Xcode will automatically derive the catalog for you upon every build

2024-01-19 22:17 UTC, philippzagar commented on Tests/UITests/TestAppUITests/TestAppUITests.swift
> +        XCTAssert(app.otherElements["Pending Message Animation"].waitForExistence(timeout: 2))
Very nice UI test, glad to see!

2024-01-19 22:17 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +        loadingDisplayMode: LoadingDisplayMode = .automatic,
I think we should provide a third option (which also should be the default!): not displaying the typing indicator at all when passing in a nil value (again, default value should be nil)

2024-01-19 22:17 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +        case manual(shouldDisplay: Binding<Bool>)
I'm not sure if a `Binding` is even necessary here, could probably be a regular `Bool`?

2024-01-19 22:17 UTC, philippzagar commented on Sources/SpeziChat/Helpers/TypingIndicator.swift
> +    TypingIndicator()
The preview is a bit misleading, try to wrap it within a message bubble and center it properly

2024-01-21 02:49 UTC, MatthewTurk247 commented on Sources/SpeziChat/Resources/Localizable.xcstrings
> +      "extractionState" : "manual",
Great catch! I think I've properly revised the string catalog now, but let me know if there is anything that I missed.

2024-01-23 04:29 UTC, MatthewTurk247 commented on Sources/SpeziChat/MessagesView.swift
> +        loadingDisplayMode: LoadingDisplayMode = .automatic,
Updated. Now the parameter is of an optional type, and if nothing is passed in, the indicator does not display.

2024-01-23 04:30 UTC, MatthewTurk247 commented on Sources/SpeziChat/MessagesView.swift
> +    /// Offers configuration of when to show an animation indicating a pending message from assistant:
Updated to "chat participant"

2024-01-23 04:35 UTC, MatthewTurk247 commented on Sources/SpeziChat/Helpers/TypingIndicator.swift
> +            .frame(width: 42, height: 12, alignment: .leading)
Here's what it looks like now
<img width="352" alt="Screenshot 2024-01-22 at 8 34 49 PM" src="https://github.com/StanfordSpezi/SpeziChat/assets/9896143/14f100f7-44ba-4f9e-84fa-c438ae3581fe">

2024-01-23 23:32 UTC, philippzagar requested changes
I left another round of review, mostly minor comments, let's bring this PR over the finish line soon! 🚀

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/ChatView.swift
> +                MessagesView($chat, loadingDisplayMode: .automatic, bottomPadding: $messageInputHeight)
I guess we should rename the parameter to `typingIndicator`? IMO, more concise and descriptive.

Also, as already stated in the last review, ensure that users of the `ChatView` can actually can set this behavior, meaning there must be a `typingIndicator` parameter in the init of the ChatView

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/Helpers/TypingIndicator.swift
> +    public var body: some View {
Thanks for the changes in here, looks way better than before! 🚀

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/Resources/Localizable.xcstrings
> +            "value" : "Pending Message Animation"
Let's name this thing "Typing Indicator" or something similar

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +        loadingDisplayMode: LoadingDisplayMode? = nil,
Great to see, nice improvement! 🚀

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +    ///   - loadingDisplayMode: Indicates whether a  "three dots" animation should be automatically or manually shown.
@MatthewTurk247

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +    private var shouldDisplayTypingIndicator: Bool {
🚀

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +    ///   - loadingDisplayMode: Indicates whether a  "three dots" animation should be automatically or manually shown.
Also, update the docs in regards to the `Optional` parameter

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +    /// `LoadingDisplayMode` has two possible cases:
Please refer to MessagesView, LoadingDisplayMode as well as the individual enum cases via the respective DocC notation with two "`", so:
- ``MessagesView``
- ``LoadingDisplayMode``
- ``LoadingDisplayMode/automatic``

2024-01-23 23:32 UTC, philippzagar commented on Sources/SpeziChat/Helpers/TypingIndicator.swift
> +#Preview {
Looks great, thank you! 🚀

2024-01-23 23:33 UTC, philippzagar commented on Sources/SpeziChat/Helpers/TypingIndicator.swift
> +            .frame(width: 42, height: 12, alignment: .leading)
Looks great, thanks you!

2024-01-23 23:40 UTC, philippzagar commented on Sources/SpeziChat/MessagesView.swift
> +    public enum LoadingDisplayMode {
I would name the enum `TypingIndicatorDisplayMode`, it's more descriptive

2024-01-24 00:20 UTC, MatthewTurk247 commented on Sources/SpeziChat/ChatView.swift
> +                MessagesView($chat, loadingDisplayMode: .automatic, bottomPadding: $messageInputHeight)
Yeah, that sounds like a great idea. I will rename and update the initializer of `ChatView`.

2024-01-25 20:58 UTC, MatthewTurk247 commented
Code comments and `README` have been updated to reflect the changes, but I will read through said changes once again for typos/errors for sake of thoroughness. To my understanding, the repository has a GitHub Action that will automatically update the documentation on the Swift Package Index based on the new `README`. Is that correct, @philippzagar?

2024-01-25 22:36 UTC, PSchmiedmayer commented
@MatthewTurk247 Thank you for the additional changes!
Thank you for updating the README! Regarding your Question: The README is used on GitHub but unfortunately is not used for the documentation generation. Is shown on GitHub and on the Swift Package Index page: https://swiftpackageindex.com/StanfordSpezi/SpeziChat

The landing page for the documentation is defined here and uses the DocC Markdown syntax: https://github.com/StanfordSpezi/SpeziChat/blob/main/Sources/SpeziChat/SpeziChat.docc/SpeziChat.md.
So you will have to duplicate the changes you made in the README to the main DocC MD page to also make them show up there and in the eventual rendered documentation at https://swiftpackageindex.com/StanfordSpezi/SpeziChat/documentation/spezichat 👍

2024-01-26 19:34 UTC, philippzagar approved these changes
Thanks @MatthewTurk247 for all the additional changes, they look great!
Great PR overall, appreciate all the effort that went into it. It's a very nice addition to SpeziChat! Feel free to merge the PR 🚀 

And yes, as soon as you merge into the `main` branch and tag a release, the online DocC documentation on the Swift Package Index page (https://swiftpackageindex.com/StanfordSpezi/SpeziChat) is updated, as already indicated by @PSchmiedmayer! 👍  

One more thing @MatthewTurk247: For future PRs, feel free to resolve the in-line comments that I had as soon as you tackled them (otherwise, the merge rules prohibit a merge). For this PR, I did that for you 😄

2024-01-26 20:01 UTC, MatthewTurk247 commented
> Thanks @MatthewTurk247 for all the additional changes, they look great! Great PR overall, appreciate all the effort that went into it. It's a very nice addition to SpeziChat! ~Feel free to merge the PR~ 🚀 EDIT: Actually, @PSchmiedmayer has to merge the PR as the commits on your branch are not signed. According to the merge rules of this repo, the merge cannot be done then (except with admin privilege). GitHub provides nice documentation on how to [set up signing commits](https://docs.github.com/articles/about-gpg/), feel free to check that out!
> 
> And yes, as soon as you merge into the `main` branch and tag a release, the online DocC documentation on the Swift Package Index page (https://swiftpackageindex.com/StanfordSpezi/SpeziChat) is updated, as already indicated by @PSchmiedmayer! 👍
> 
> One more thing @MatthewTurk247: For future PRs, feel free to resolve the in-line comments that I had as soon as you tackled them (otherwise, the merge rules prohibit a merge). For this PR, I did that for you 😄

Gotcha. Thank you very much for reviewing this PR and providing guidance throughout the process! I'll be sure to set up signing commits moving forward.

2024-01-26 20:05 UTC, PSchmiedmayer commented
Thank you @MatthewTurk247 for the PR and improving Spezi Chat and thank you @philippzagar for the great reviews!
I will mere the branch 👍

2024-01-26 20:05 UTC, merged